### ISSUE TITLE
Feature detail tables don't open on click

### ISSUE THREAD

**Issue by pjsier** [SolutionGuidance/psm-dashboard#26]
Clicking any of the feature rows results in `TypeError: row is undefined`. This likely caused by the features data being updated recently

**Comment by pjsier** [comment]
@kfogel it looks like this is a data issue. When I ran the `refresh-dashboard` script, it emptied all of the requirements ([see the diff here](https://github.com/SolutionGuidance/psm-dashboard/commit/5f6799f419e0bf82a1da1ee44d36f2c74b0923ad#diff-960ffb52b99217dd41aff71bf6d33192R1028)). Is there anything environment specific about the script that I might have missed?

**Comment by kfogel** [comment]
@pjsier Whoa.  Between your previous (successful) run and this run just now, nothing about `gather-inputs` nor the requirements data has changed, right?

Oh, I can think of one thing: if your local PSM repository is still on the `gh-pages` branch instead of on `master`, then your `psm-dashboard-config.json` file is probably pointing at a location for `requirements/RTM.xlsx` that does not exist, because that stuff isn't on the `gh-pages` branch :-).  Is that it?

**Comment by pjsier** [comment]
@kfogel I thought that was it, and I was on the `gh-pages` branch, but I just ran the script again and it's still empty. In theory, the check for whether RTM.xslx exists should have resolved this, but even when the file is in the correct spot `xlsx2csv` outputs an empty RTM.csv file. Running `xlsx2csv` produces the correct output though

**Comment by pjsier** [comment]
Closing as a duplicate of #14 because the problem is relating to the `RTM_XLSX` var not getting passed, which is only necessary because we're converting that manually
