### ISSUE TITLE
Burn-down chart pop-ups don't work well inside iframe

### ISSUE THREAD

**Issue by PaulMorris** [SolutionGuidance/psm-dashboard#33]
When you click one of the feature rows the pop-up overlay is shown inside the iframe.  Compare clicking the rows [here](https://solutionguidance.github.io/psm-dashboard/) and [on projectpsm.org](http://projectpsm.org/dashboard/).  Instead of being centered in the visible browser viewport where you can immediately see what you want, the iframe is the pop-up overlay's viewport so you usually have to scroll up to see anything, and to access the close button, losing your place on the page.  (Also you can't click anywhere outside the popup to close it, you have to click the narrow strip that's outside it but still inside the iframe.)

**Comment by PaulMorris** [comment]
Some possible solutions include:

1. Size the iframe so it's not so tall, ideally fitting snugly inside the visible viewport of its containing page, then you would scroll the iframe's contents inside the iframe.  Would likely create an unpleasant "scrolling a window nested inside a scrolling window" effect.

2. Move the pop-up overlay code outside the iframe to the parent page context and pass messages with JSON data to display the overlay on the parent page.  (Would the jekyll site allow this kind of thing?)

3. Don't use an iframe and render the dashboard contents on the page itself.  Would require some reworking.  (Does the jekyll site allow this?)

4. Don't use an iframe, but (if 3 won't work) set up a web page for the dashboard outside of the jekyll static site, and set up links between the two.  Probably have same/similar header and main navigation links so users wouldn't notice the difference when navigating to/from the dashboard.

**Comment by kfogel** [comment]
Thanks, @PaulMorris -- nice work (on resolving #30 and #32).  I'm okay with any of the above solutions that give us the user-visible result we need.  I don't know enough about iframe advantages and disadvantages to have a truly informed opinion, but my impression from reading the above is that "just ditch the iframe" (i.e., option 3 or 4) is probably the best answer right now.  Reasoning: even if there *is* a workable solution that involves an iframe, it sounds like it'll take a while to come up with that solution, and in the meantime a no-iframe solution is a tiny investment -- all one has to do is get rid of the iframe and maybe duplicate some headers and navigation links.  While that's not a great long-term maintainability situation, it solves the immediate problem and does not actually accumulate much debt (since it's so easy to do and would, assuming the presence of an eventual iframe-friendly solution, be very easy to undo as well).  And there is some urgency to solving the immediate problem: people are actually looking at this page and we need it to be as easy for them to understand and use as possible.

Here's a link to the [Zulip conversation about this issue](https://chat.opentechstrategies.com/#narrow/stream/6-Provider-Screening/subject/dashboard/near/52209).

**Comment by PaulMorris** [comment]
After a phone conversation with @kfogel we have a plan for resolving this issue and simplifying the way the dashboard is integrated into the projectpsm.org site.  As @kfogel [summarized on zulip](https://chat.opentechstrategies.com/#narrow/stream/6-Provider-Screening/subject/dashboard/near/52240):

> Summary: all front-facing dashboard stuff is going to move from the `psm-dashboard` repository over to the `gh-pages` branch of the main `psm` repository, while the back-end dashboard stuff will stay maintained where it is now. The `features-info.json` file, which is the bridge between the two, will now be checked in in the `gh-pages` branch in the PSM repository, instead of the dashboard repository where it lives currently. This decision will simplify a lot of things.

The front-facing files that will move include the upstream and local JS files, HTML, CSS, and the `features-info.json` data file (that will be checked in).  Then, rather than loading the dashboard into an iframe with pym.js, we can create a static dashboard page that's a first-class page in the jekyll static site, with `<script>` tags, etc.  This means the CSS from the static site (`main.css`) will also affect the dashboard charts, but any conflicts there should be manageable.  Not having the dashboard in an iframe will simplify development and resolve this issue with the pop-ups not working well inside the iframe.

**Comment by PaulMorris** [comment]
This issue has been resolved by this commit on the `gh-pages` branch of the `psm` repo:
https://github.com/SolutionGuidance/psm/commit/eea0afb94e5a338408fb3f69d6f1a96cd1bfe0ee

I'll be doing some follow-up commits to complete the transition of moving files from this repo to that one.
