### ISSUE TITLE
Burn-down chart: two rows fail to pop up tooltip window on click.

### ISSUE THREAD

**Issue by kfogel** [SolutionGuidance/psm-dashboard#39]
As of right now (commit e7f49942e in PSM `gh-pages`, and commit 283cdc9a23 in the dashboard), these two rows in the burn-down chart fail to pop up the expected tooltip window when clicked on:

    Add new fields for specific requirements relating to bordering-state providers, care settings, help, etc.

    Documentation updates and help-text integration

(I believe that is a complete list -- I tested every row, though admittedly it's such an eye-glazing task that I can't be 100% sure that I didn't accidentally skip any.)

I have no idea why those particular rows are buggy.  So far, I haven't figured out what specialness they have in common.

**Comment by PaulMorris** [comment]
Fixed with commits:
  - Strip any extra whitespace from `req_id`s when generating JSON: https://github.com/SolutionGuidance/psm-dashboard/commit/059ccbd5dde30cefd70ba7210dc0823e456a513d 
  - Add defensive measures vs failure to access req data on dashboard: https://github.com/SolutionGuidance/psm/commit/82f5fef3b8b2d492df795837fd6c72fbdc91ecfe
  - Remove trailing space in "psm-FR-7.15 " in features-info.json: https://github.com/SolutionGuidance/psm/commit/09da2c678e98550f00ca1dabcf9432ee7bfa21d1
