### ISSUE TITLE
Show future roadmap on burndown chart

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm-dashboard#8]
This will make the burndown chart into more of a Gantt chart for project planning.  Extend the bars into the future, using estimated start and end dates.  These can live in the Start Date / End Date columns in the spreadsheet, and will simply be future dates.  I'd suggest using a washed-out version of the same colors in the future, so the "Today" line is still clearly delineated but users can see when we expect to do various features that haven't yet been started.

**Comment by kfogel** [comment]
Hey @pjsier -- reopening this because my chart is still not showing anything to the right of the orange line.  Commit e60ab107da is in `master` now & my local dev tree is up-to-date.  I did a fresh run of `refresh-dashboard` (which resulted in no changes to `features-info.json`, as expected).  I've made doubly sure that `psm-dashboard-config.json` says:

     "google_sheet_range": "Features"

too -- IOW no column range restriction is given.

Any ideas?  (See also my question in closed PR #21.  What I'm seeing locally is not like your screenshots there, but even your screenshots didn't show the behavior this enhancement is going for -- though perhaps we just didn't communicate it clearly.)
